class CSSStyleDeclarationLight {
  constructor(cssFromSite) {
    this.styles = CSSDictionary();
    this.fromSite = cssFromSite;
    this.selectors = ['font-family', 'font-weight', 'font-size', 'border', 'padding', 'color', 'background-color'];
    this.regexCleaner = /!important/
  }

  getPropertyValue(property) {
    return this.styles[property];
  }

  getComputedStyle(tagType, classNames) {
    const filtered = this.fromSite.filter(e => e.selector.includes(tagType) || e.selector.includes(classNames))

    filtered.map(e => {
      if (e && e.rules) {
        e.rules.map(r => {
          if (this.selectors.includes((r.directive))) {
            let currentValue = r.value
            currentValue = currentValue.replace(this.regexCleaner, "");

            this.styles[r.directive] = currentValue;
          }
        })
      }
    })

    return this.styles;
  }
}


// This styles from window.getComputedStyle function
// since we are not using headless anymore
// we should handle all the styles in our code by ourselves.
function CSSDictionary() {
  return {
    // "accentColor": "auto",
    // "additiveSymbols": "",
    // "alignContent": "normal",
    // "alignItems": "normal",
    // "alignSelf": "auto",
    // "alignmentBaseline": "auto",
    // "all": "",
    // "animation": "none 0s ease 0s 1 normal none running",
    // "animationComposition": "replace",
    // "animationDelay": "0s",
    // "animationDirection": "normal",
    // "animationDuration": "0s",
    // "animationFillMode": "none",
    // "animationIterationCount": "1",
    // "animationName": "none",
    // "animationPlayState": "running",
    // "animationRange": "normal",
    // "animationRangeEnd": "normal",
    // "animationRangeStart": "normal",
    // "animationTimeline": "auto",
    // "animationTimingFunction": "ease",
    // "appRegion": "none",
    // "appearance": "none",
    // "ascentOverride": "",
    // "aspectRatio": "auto",
    // "backdropFilter": "none",
    // "backfaceVisibility": "visible",
    "background": "rgb(255, 255, 255) none repeat scroll 0% 0% / auto padding-box border-box",
    // "backgroundAttachment": "scroll",
    // "backgroundBlendMode": "normal",
    // "backgroundClip": "border-box",
    // "backgroundColor": "rgb(255, 255, 255)",
    // "backgroundImage": "none",
    // "backgroundOrigin": "padding-box",
    // "backgroundPosition": "0% 0%",
    // "backgroundPositionX": "0%",
    // "backgroundPositionY": "0%",
    // "backgroundRepeat": "repeat",
    // "backgroundRepeatX": "repeat",
    // "backgroundRepeatY": "repeat",
    // "backgroundSize": "auto",
    // "basePalette": "",
    // "baselineShift": "0px",
    // "baselineSource": "auto",
    // "blockSize": "4085.43px",
    "border": "none",
    // "borderBlock": "0px none rgb(35, 38, 41)",
    // "borderBlockColor": "rgb(35, 38, 41)",
    // "borderBlockEnd": "0px none rgb(35, 38, 41)",
    // "borderBlockEndColor": "rgb(35, 38, 41)",
    // "borderBlockEndStyle": "none",
    // "borderBlockEndWidth": "0px",
    // "borderBlockStart": "0px none rgb(35, 38, 41)",
    // "borderBlockStartColor": "rgb(35, 38, 41)",
    // "borderBlockStartStyle": "none",
    // "borderBlockStartWidth": "0px",
    // "borderBlockStyle": "none",
    // "borderBlockWidth": "0px",
    // "borderBottom": "0px none rgb(35, 38, 41)",
    // "borderBottomColor": "rgb(35, 38, 41)",
    // "borderBottomLeftRadius": "0px",
    // "borderBottomRightRadius": "0px",
    // "borderBottomStyle": "none",
    // "borderBottomWidth": "0px",
    // "borderCollapse": "separate",
    // "borderColor": "rgb(35, 38, 41)",
    // "borderEndEndRadius": "0px",
    // "borderEndStartRadius": "0px",
    // "borderImage": "none",
    // "borderImageOutset": "0",
    // "borderImageRepeat": "stretch",
    // "borderImageSlice": "100%",
    // "borderImageSource": "none",
    // "borderImageWidth": "1",
    // "borderInline": "0px none rgb(35, 38, 41)",
    // "borderInlineColor": "rgb(35, 38, 41)",
    // "borderInlineEnd": "0px none rgb(35, 38, 41)",
    // "borderInlineEndColor": "rgb(35, 38, 41)",
    // "borderInlineEndStyle": "none",
    // "borderInlineEndWidth": "0px",
    // "borderInlineStart": "0px none rgb(35, 38, 41)",
    // "borderInlineStartColor": "rgb(35, 38, 41)",
    // "borderInlineStartStyle": "none",
    // "borderInlineStartWidth": "0px",
    // "borderInlineStyle": "none",
    // "borderInlineWidth": "0px",
    // "borderLeft": "0px none rgb(35, 38, 41)",
    // "borderLeftColor": "rgb(35, 38, 41)",
    // "borderLeftStyle": "none",
    // "borderLeftWidth": "0px",
    // "borderRadius": "0px",
    // "borderRight": "0px none rgb(35, 38, 41)",
    // "borderRightColor": "rgb(35, 38, 41)",
    // "borderRightStyle": "none",
    // "borderRightWidth": "0px",
    // "borderSpacing": "0px 0px",
    // "borderStartEndRadius": "0px",
    // "borderStartStartRadius": "0px",
    // "borderStyle": "none",
    // "borderTop": "0px none rgb(35, 38, 41)",
    // "borderTopColor": "rgb(35, 38, 41)",
    // "borderTopLeftRadius": "0px",
    // "borderTopRightRadius": "0px",
    // "borderTopStyle": "none",
    // "borderTopWidth": "0px",
    // "borderWidth": "0px",
    // "bottom": "auto",
    // "boxShadow": "none",
    // "boxSizing": "border-box",
    // "breakAfter": "auto",
    // "breakBefore": "auto",
    // "breakInside": "auto",
    // "bufferedRendering": "auto",
    // "captionSide": "top",
    // "caretColor": "rgb(35, 38, 41)",
    // "clear": "none",
    // "clip": "auto",
    // "clipPath": "none",
    // "clipRule": "nonzero",
    "color": "rgb(35, 38, 41)",
    // "colorInterpolation": "srgb",
    // "colorInterpolationFilters": "linearrgb",
    // "colorRendering": "auto",
    // "colorScheme": "normal",
    // "columnCount": "auto",
    // "columnFill": "balance",
    // "columnGap": "normal",
    // "columnRule": "0px none rgb(35, 38, 41)",
    // "columnRuleColor": "rgb(35, 38, 41)",
    // "columnRuleStyle": "none",
    // "columnRuleWidth": "0px",
    // "columnSpan": "none",
    // "columnWidth": "auto",
    // "columns": "auto auto",
    // "contain": "none",
    // "containIntrinsicBlockSize": "none",
    // "containIntrinsicHeight": "none",
    // "containIntrinsicInlineSize": "none",
    // "containIntrinsicSize": "none",
    // "containIntrinsicWidth": "none",
    // "container": "none",
    // "containerName": "none",
    // "containerType": "normal",
    // "content": "normal",
    // "contentVisibility": "visible",
    // "counterIncrement": "none",
    // "counterReset": "none",
    // "counterSet": "none",
    // "cursor": "auto",
    // "cx": "0px",
    // "cy": "0px",
    // "d": "none",
    // "descentOverride": "",
    // "direction": "ltr",
    // "display": "flex",
    // "dominantBaseline": "auto",
    // "emptyCells": "show",
    // "fallback": "",
    // "fill": "rgb(0, 0, 0)",
    // "fillOpacity": "1",
    // "fillRule": "nonzero",
    // "filter": "none",
    // "flex": "0 1 auto",
    // "flexBasis": "auto",
    // "flexDirection": "column",
    // "flexFlow": "column nowrap",
    // "flexGrow": "0",
    // "flexShrink": "1",
    // "flexWrap": "nowrap",
    // "float": "none",
    // "floodColor": "rgb(0, 0, 0)",
    // "floodOpacity": "1",
    // "font": "11px / 14.3846px -apple-system, \"system-ui\", \"Segoe UI Adjusted\", \"Segoe UI\", \"Liberation Sans\", sans-serif",
    // "fontDisplay": "",
    "font-family": "-apple-system, \"system-ui\", \"Segoe UI Adjusted\", \"Segoe UI\", \"Liberation Sans\", sans-serif",
    // "fontFeatureSettings": "normal",
    // "fontKerning": "auto",
    // "fontOpticalSizing": "auto",
    // "fontPalette": "normal",
    "font-size": "11px",
    // "fontStretch": "100%",
    // "fontStyle": "normal",
    // "fontSynthesis": "weight style small-caps",
    // "fontSynthesisSmallCaps": "auto",
    // "fontSynthesisStyle": "auto",
    // "fontSynthesisWeight": "auto",
    // "fontVariant": "normal",
    // "fontVariantAlternates": "normal",
    // "fontVariantCaps": "normal",
    // "fontVariantEastAsian": "normal",
    // "fontVariantLigatures": "normal",
    // "fontVariantNumeric": "normal",
    // "fontVariationSettings": "normal",
    "font-weight": "400",
    // "forcedColorAdjust": "auto",
    // "gap": "normal",
    // "grid": "none / none / none / row / auto / auto",
    // "gridArea": "auto / auto / auto / auto",
    // "gridAutoColumns": "auto",
    // "gridAutoFlow": "row",
    // "gridAutoRows": "auto",
    // "gridColumn": "auto / auto",
    // "gridColumnEnd": "auto",
    // "gridColumnGap": "normal",
    // "gridColumnStart": "auto",
    // "gridGap": "normal normal",
    // "gridRow": "auto / auto",
    // "gridRowEnd": "auto",
    // "gridRowGap": "normal",
    // "gridRowStart": "auto",
    // "gridTemplate": "none / none / none",
    // "gridTemplateAreas": "none",
    // "gridTemplateColumns": "none",
    // "gridTemplateRows": "none",
    // "height": "4085.43px",
    // "hyphenateCharacter": "auto",
    // "hyphenateLimitChars": "auto",
    // "hyphens": "manual",
    // "imageOrientation": "from-image",
    // "imageRendering": "auto",
    // "inherits": "",
    // "initialLetter": "normal",
    // "initialValue": "",
    // "inlineSize": "465px",
    // "inset": "auto",
    // "insetBlock": "auto",
    // "insetBlockEnd": "auto",
    // "insetBlockStart": "auto",
    // "insetInline": "auto",
    // "insetInlineEnd": "auto",
    // "insetInlineStart": "auto",
    // "isolation": "auto",
    // "justifyContent": "normal",
    // "justifyItems": "normal",
    // "justifySelf": "auto",
    // "left": "auto",
    // "letterSpacing": "normal",
    // "lightingColor": "rgb(255, 255, 255)",
    // "lineBreak": "auto",
    // "lineGapOverride": "",
    // "lineHeight": "14.3846px",
    // "listStyle": "outside none disc",
    // "listStyleImage": "none",
    // "listStylePosition": "outside",
    // "listStyleType": "disc",
    // "margin": "0px",
    // "marginBlock": "0px",
    // "marginBlockEnd": "0px",
    // "marginBlockStart": "0px",
    // "marginBottom": "0px",
    // "marginInline": "0px",
    // "marginInlineEnd": "0px",
    // "marginInlineStart": "0px",
    // "marginLeft": "0px",
    // "marginRight": "0px",
    // "marginTop": "0px",
    // "marker": "none",
    // "markerEnd": "none",
    // "markerMid": "none",
    // "markerStart": "none",
    // "mask": "none",
    // "maskType": "luminance",
    // "mathDepth": "0",
    // "mathShift": "normal",
    // "mathStyle": "normal",
    // "maxBlockSize": "none",
    // "maxHeight": "none",
    // "maxInlineSize": "none",
    // "maxWidth": "none",
    // "minBlockSize": "100%",
    // "minHeight": "100%",
    // "minInlineSize": "0px",
    // "minWidth": "0px",
    // "mixBlendMode": "normal",
    // "negative": "",
    // "objectFit": "fill",
    // "objectPosition": "50% 50%",
    // "objectViewBox": "none",
    // "offset": "none 0px auto 0deg",
    // "offsetDistance": "0px",
    // "offsetPath": "none",
    // "offsetRotate": "auto 0deg",
    // "opacity": "1",
    // "order": "0",
    // "orphans": "2",
    // "outline": "rgb(35, 38, 41) none 0px",
    // "outlineColor": "rgb(35, 38, 41)",
    // "outlineOffset": "0px",
    // "outlineStyle": "none",
    // "outlineWidth": "0px",
    // "overflow": "visible",
    // "overflowAnchor": "auto",
    // "overflowClipMargin": "0px",
    // "overflowWrap": "normal",
    // "overflowX": "visible",
    // "overflowY": "visible",
    // "overrideColors": "",
    // "overscrollBehavior": "auto",
    // "overscrollBehaviorBlock": "auto",
    // "overscrollBehaviorInline": "auto",
    // "overscrollBehaviorX": "auto",
    // "overscrollBehaviorY": "auto",
    // "pad": "",
    "padding": "0px 0px 0px 0px",
    // "paddingBlock": "56px 0px",
    // "paddingBlockEnd": "0px",
    // "paddingBlockStart": "56px",
    // "paddingBottom": "0px",
    // "paddingInline": "0px",
    // "paddingInlineEnd": "0px",
    // "paddingInlineStart": "0px",
    // "paddingLeft": "0px",
    // "paddingRight": "0px",
    // "paddingTop": "56px",
    // "page": "auto",
    // "pageBreakAfter": "auto",
    // "pageBreakBefore": "auto",
    // "pageBreakInside": "auto",
    // "pageOrientation": "",
    // "paintOrder": "normal",
    // "perspective": "none",
    // "perspectiveOrigin": "232.5px 2042.71px",
    // "placeContent": "normal",
    // "placeItems": "normal",
    // "placeSelf": "auto",
    // "pointerEvents": "auto",
    // "position": "static",
    // "prefix": "",
    // "quotes": "auto",
    // "r": "0px",
    // "range": "",
    // "resize": "none",
    // "right": "auto",
    // "rotate": "none",
    // "rowGap": "normal",
    // "rubyPosition": "over",
    // "rx": "auto",
    // "ry": "auto",
    // "scale": "none",
    // "scrollBehavior": "auto",
    // "scrollMargin": "0px",
    // "scrollMarginBlock": "0px",
    // "scrollMarginBlockEnd": "0px",
    // "scrollMarginBlockStart": "0px",
    // "scrollMarginBottom": "0px",
    // "scrollMarginInline": "0px",
    // "scrollMarginInlineEnd": "0px",
    // "scrollMarginInlineStart": "0px",
    // "scrollMarginLeft": "0px",
    // "scrollMarginRight": "0px",
    // "scrollMarginTop": "0px",
    // "scrollPadding": "auto",
    // "scrollPaddingBlock": "auto",
    // "scrollPaddingBlockEnd": "auto",
    // "scrollPaddingBlockStart": "auto",
    // "scrollPaddingBottom": "auto",
    // "scrollPaddingInline": "auto",
    // "scrollPaddingInlineEnd": "auto",
    // "scrollPaddingInlineStart": "auto",
    // "scrollPaddingLeft": "auto",
    // "scrollPaddingRight": "auto",
    // "scrollPaddingTop": "auto",
    // "scrollSnapAlign": "none",
    // "scrollSnapStop": "normal",
    // "scrollSnapType": "none",
    // "scrollTimeline": "none",
    // "scrollTimelineAxis": "block",
    // "scrollTimelineName": "none",
    // "scrollbarGutter": "auto",
    // "shapeImageThreshold": "0",
    // "shapeMargin": "0px",
    // "shapeOutside": "none",
    // "shapeRendering": "auto",
    // "size": "",
    // "sizeAdjust": "",
    // "speak": "normal",
    // "speakAs": "",
    // "src": "",
    // "stopColor": "rgb(0, 0, 0)",
    // "stopOpacity": "1",
    // "stroke": "none",
    // "strokeDasharray": "none",
    // "strokeDashoffset": "0px",
    // "strokeLinecap": "butt",
    // "strokeLinejoin": "miter",
    // "strokeMiterlimit": "4",
    // "strokeOpacity": "1",
    // "strokeWidth": "1px",
    // "suffix": "",
    // "symbols": "",
    // "syntax": "",
    // "system": "",
    // "tabSize": "8",
    // "tableLayout": "auto",
    // "textAlign": "start",
    // "textAlignLast": "auto",
    // "textAnchor": "start",
    // "textCombineUpright": "none",
    // "textDecoration": "none solid rgb(35, 38, 41)",
    // "textDecorationColor": "rgb(35, 38, 41)",
    // "textDecorationLine": "none",
    // "textDecorationSkipInk": "auto",
    // "textDecorationStyle": "solid",
    // "textDecorationThickness": "auto",
    // "textEmphasis": "none rgb(35, 38, 41)",
    // "textEmphasisColor": "rgb(35, 38, 41)",
    // "textEmphasisPosition": "over",
    // "textEmphasisStyle": "none",
    // "textIndent": "0px",
    // "textOrientation": "mixed",
    // "textOverflow": "clip",
    // "textRendering": "auto",
    // "textShadow": "none",
    // "textSizeAdjust": "auto",
    // "textTransform": "none",
    // "textUnderlineOffset": "auto",
    // "textUnderlinePosition": "auto",
    // "textWrap": "wrap",
    // "top": "auto",
    // "touchAction": "auto",
    // "transform": "none",
    // "transformBox": "view-box",
    // "transformOrigin": "232.5px 2042.71px",
    // "transformStyle": "flat",
    // "transition": "all 0s ease 0s",
    // "transitionDelay": "0s",
    // "transitionDuration": "0s",
    // "transitionProperty": "all",
    // "transitionTimingFunction": "ease",
    // "translate": "none",
    // "unicodeBidi": "normal",
    // "unicodeRange": "",
    // "userSelect": "auto",
    // "vectorEffect": "none",
    // "verticalAlign": "baseline",
    // "viewTimeline": "none",
    // "viewTimelineAxis": "block",
    // "viewTimelineInset": "0px",
    // "viewTimelineName": "none",
    // "viewTransitionName": "none",
    // "visibility": "visible",
    // "webkitAlignContent": "normal",
    // "webkitAlignItems": "normal",
    // "webkitAlignSelf": "auto",
    // "webkitAnimation": "none 0s ease 0s 1 normal none running",
    // "webkitAnimationDelay": "0s",
    // "webkitAnimationDirection": "normal",
    // "webkitAnimationDuration": "0s",
    // "webkitAnimationFillMode": "none",
    // "webkitAnimationIterationCount": "1",
    // "webkitAnimationName": "none",
    // "webkitAnimationPlayState": "running",
    // "webkitAnimationTimingFunction": "ease",
    // "webkitAppRegion": "none",
    // "webkitAppearance": "none",
    // "webkitBackfaceVisibility": "visible",
    // "webkitBackgroundClip": "border-box",
    // "webkitBackgroundOrigin": "padding-box",
    // "webkitBackgroundSize": "auto",
    // "webkitBorderAfter": "0px none rgb(35, 38, 41)",
    // "webkitBorderAfterColor": "rgb(35, 38, 41)",
    // "webkitBorderAfterStyle": "none",
    // "webkitBorderAfterWidth": "0px",
    // "webkitBorderBefore": "0px none rgb(35, 38, 41)",
    // "webkitBorderBeforeColor": "rgb(35, 38, 41)",
    // "webkitBorderBeforeStyle": "none",
    // "webkitBorderBeforeWidth": "0px",
    // "webkitBorderBottomLeftRadius": "0px",
    // "webkitBorderBottomRightRadius": "0px",
    // "webkitBorderEnd": "0px none rgb(35, 38, 41)",
    // "webkitBorderEndColor": "rgb(35, 38, 41)",
    // "webkitBorderEndStyle": "none",
    // "webkitBorderEndWidth": "0px",
    // "webkitBorderHorizontalSpacing": "0px",
    // "webkitBorderImage": "none",
    // "webkitBorderRadius": "0px",
    // "webkitBorderStart": "0px none rgb(35, 38, 41)",
    // "webkitBorderStartColor": "rgb(35, 38, 41)",
    // "webkitBorderStartStyle": "none",
    // "webkitBorderStartWidth": "0px",
    // "webkitBorderTopLeftRadius": "0px",
    // "webkitBorderTopRightRadius": "0px",
    // "webkitBorderVerticalSpacing": "0px",
    // "webkitBoxAlign": "stretch",
    // "webkitBoxDecorationBreak": "slice",
    // "webkitBoxDirection": "normal",
    // "webkitBoxFlex": "0",
    // "webkitBoxOrdinalGroup": "1",
    // "webkitBoxOrient": "horizontal",
    // "webkitBoxPack": "start",
    // "webkitBoxReflect": "none",
    // "webkitBoxShadow": "none",
    // "webkitBoxSizing": "border-box",
    // "webkitClipPath": "none",
    // "webkitColumnBreakAfter": "auto",
    // "webkitColumnBreakBefore": "auto",
    // "webkitColumnBreakInside": "auto",
    // "webkitColumnCount": "auto",
    // "webkitColumnGap": "normal",
    // "webkitColumnRule": "0px none rgb(35, 38, 41)",
    // "webkitColumnRuleColor": "rgb(35, 38, 41)",
    // "webkitColumnRuleStyle": "none",
    // "webkitColumnRuleWidth": "0px",
    // "webkitColumnSpan": "none",
    // "webkitColumnWidth": "auto",
    // "webkitColumns": "auto auto",
    // "webkitFilter": "none",
    // "webkitFlex": "0 1 auto",
    // "webkitFlexBasis": "auto",
    // "webkitFlexDirection": "column",
    // "webkitFlexFlow": "column nowrap",
    // "webkitFlexGrow": "0",
    // "webkitFlexShrink": "1",
    // "webkitFlexWrap": "nowrap",
    // "webkitFontFeatureSettings": "normal",
    // "webkitFontSmoothing": "auto",
    // "webkitHighlight": "none",
    // "webkitHyphenateCharacter": "auto",
    // "webkitJustifyContent": "normal",
    // "webkitLineBreak": "auto",
    // "webkitLineClamp": "none",
    // "webkitLocale": "\"en\"",
    // "webkitLogicalHeight": "4085.43px",
    // "webkitLogicalWidth": "465px",
    // "webkitMarginAfter": "0px",
    // "webkitMarginBefore": "0px",
    // "webkitMarginEnd": "0px",
    // "webkitMarginStart": "0px",
    // "webkitMask": "",
    // "webkitMaskBoxImage": "none",
    // "webkitMaskBoxImageOutset": "0",
    // "webkitMaskBoxImageRepeat": "stretch",
    // "webkitMaskBoxImageSlice": "0 fill",
    // "webkitMaskBoxImageSource": "none",
    // "webkitMaskBoxImageWidth": "auto",
    // "webkitMaskClip": "border-box",
    // "webkitMaskComposite": "source-over",
    // "webkitMaskImage": "none",
    // "webkitMaskOrigin": "border-box",
    // "webkitMaskPosition": "0% 0%",
    // "webkitMaskPositionX": "0%",
    // "webkitMaskPositionY": "0%",
    // "webkitMaskRepeat": "repeat",
    // "webkitMaskRepeatX": "",
    // "webkitMaskRepeatY": "",
    // "webkitMaskSize": "auto",
    // "webkitMaxLogicalHeight": "none",
    // "webkitMaxLogicalWidth": "none",
    // "webkitMinLogicalHeight": "100%",
    // "webkitMinLogicalWidth": "0px",
    // "webkitOpacity": "1",
    // "webkitOrder": "0",
    // "webkitPaddingAfter": "0px",
    // "webkitPaddingBefore": "56px",
    // "webkitPaddingEnd": "0px",
    // "webkitPaddingStart": "0px",
    // "webkitPerspective": "none",
    // "webkitPerspectiveOrigin": "232.5px 2042.71px",
    // "webkitPerspectiveOriginX": "",
    // "webkitPerspectiveOriginY": "",
    // "webkitPrintColorAdjust": "economy",
    // "webkitRtlOrdering": "logical",
    // "webkitRubyPosition": "before",
    // "webkitShapeImageThreshold": "0",
    // "webkitShapeMargin": "0px",
    // "webkitShapeOutside": "none",
    // "webkitTapHighlightColor": "rgba(0, 0, 0, 0.18)",
    // "webkitTextCombine": "none",
    // "webkitTextDecorationsInEffect": "none",
    // "webkitTextEmphasis": "none rgb(35, 38, 41)",
    // "webkitTextEmphasisColor": "rgb(35, 38, 41)",
    // "webkitTextEmphasisPosition": "over",
    // "webkitTextEmphasisStyle": "none",
    // "webkitTextFillColor": "rgb(35, 38, 41)",
    // "webkitTextOrientation": "vertical-right",
    // "webkitTextSecurity": "none",
    // "webkitTextSizeAdjust": "auto",
    // "webkitTextStroke": "",
    // "webkitTextStrokeColor": "rgb(35, 38, 41)",
    // "webkitTextStrokeWidth": "0px",
    // "webkitTransform": "none",
    // "webkitTransformOrigin": "232.5px 2042.71px",
    // "webkitTransformOriginX": "",
    // "webkitTransformOriginY": "",
    // "webkitTransformOriginZ": "",
    // "webkitTransformStyle": "flat",
    // "webkitTransition": "all 0s ease 0s",
    // "webkitTransitionDelay": "0s",
    // "webkitTransitionDuration": "0s",
    // "webkitTransitionProperty": "all",
    // "webkitTransitionTimingFunction": "ease",
    // "webkitUserDrag": "auto",
    // "webkitUserModify": "read-only",
    // "webkitUserSelect": "auto",
    // "webkitWritingMode": "horizontal-tb",
    // "whiteSpace": "normal",
    // "whiteSpaceCollapse": "collapse",
    // "widows": "2",
    // "width": "0px",
    // "willChange": "auto",
    // "wordBreak": "normal",
    // "wordSpacing": "0px",
    // "wordWrap": "normal",
    // "writingMode": "horizontal-tb",
    // "x": "0px",
    // "y": "0px",
    // "zIndex": "auto",
    // "zoom": "1"
  }
}

export default CSSStyleDeclarationLight;
